### ISSUE TITLE
cli docs say that 'method' param is optional in routes.js, but it doesn't seem to be

### ISSUE THREAD

**Issue by kcjonson** [redfin/react-server#105]
The cli getting started guide says that 'method' is optional, but for a very basic test, it didn't seem to be.  Does it default to `POST`?  This seems like an odd default.

**Comment by aickin** [comment]
Making that options was just [merged to master yesterday](https://github.com/redfin/react-server/pull/100), and may not have been published to npm yet. are you using master or a published version?

**Comment by gigabo** [comment]
This went out with `0.2.0` yesterday.  Thanks for reporting @kcjonson!
