### ISSUE TITLE
non-absolute URLs in stylesheets cause client-side stylesheet resolution machinery to replace stylesheets

### ISSUE THREAD

**Issue by roblg** [redfin/react-server#116]
I noticed this while working on https://github.com/redfin/react-server/pull/115

It seems like if the server returns a relative URL for a stylesheet, the client-side code in ClientCssHelper sees an absolute URL in the document, and when it compares that to the relative URL returned by getHeadStylesheets client-side, it thinks they're different and replaces them.

I didn't have time to investigate deeply, but I _think_ this is what's happening. (I don't think it's something that #115 introduced)

**Comment by gigabo** [comment]
I _think_ this was fixed by #501.  @roblg does that look right?

**Comment by roblg** [comment]
Seems plausible, yep.
