### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#119]
Can't be taken seriously without a cute picture to represent the project, right?

**Comment by gigabo** [comment]
@mahalie - Pretty please? 🙏

**Comment by kcjonson** [comment]
![logo](https://cloud.githubusercontent.com/assets/1512633/14929687/9558a36a-0e13-11e6-9eed-63c0bd7b32b3.png)

**Comment by gigabo** [comment]
@kcjonson - oooOOOOOoooohhhh!

But... don't we want something square-ish?  Seems like most logos are either square or landscape.

**Comment by gigabo** [comment]
Other examples of logos in the React ecosystem:

https://github.com/react-bootstrap
https://github.com/Legitcode
https://github.com/rackt

**Comment by careylin** [comment]
@doug-wade mentioned to me that y'all were looking for a little logo, I could play around with some things and send you guys some ideas

**Comment by gigabo** [comment]
Thanks @careylin!

**Comment by mahalie** [comment]
Hi there, just seeing this. My github mentions go to my personal email account (and get filtered into 'Forums' apparently). Didn't know Redfin had a Github repo 🏭 

Here's some quick 'react server' icon explorations. I'll checking with @careylin and see what she's got going as well before spending any more time on it.   

![image](https://cloud.githubusercontent.com/assets/119383/14995904/3071c58c-112c-11e6-8dc4-f4fcba6f2d57.png)

**Comment by doug-wade** [comment]
I dig https://cloud.githubusercontent.com/assets/119383/14995904/3071c58c-112c-11e6-8dc4-f4fcba6f2d57.png

**Comment by doug-wade** [comment]
I dig <img width="110" alt="screen shot 2016-05-03 at 12 49 52 pm" src="https://cloud.githubusercontent.com/assets/3477707/14996181/95538304-112d-11e6-96bb-56f76bf73611.png">

**Comment by mahalie** [comment]
Carey was able to spend some time Friday and has some neat isometric options. Stay tuned.

**Comment by careylin** [comment]
Me and mahalez are on the same thought train hah. I did some silly stuff, but these were the actual good stuffs <img width="1067" alt="screen shot 2016-05-03 at 1 01 54 pm" src="https://cloud.githubusercontent.com/assets/8015761/14996518/3eee744a-112f-11e6-9d42-e4e2426b8283.png">

**Comment by doug-wade** [comment]
I vote 
<img width="181" alt="screen shot 2016-05-03 at 1 47 23 pm" src="https://cloud.githubusercontent.com/assets/3477707/14997841/9d626f08-1135-11e6-8990-8cce5a3624bc.png">

**Comment by jmhwang7** [comment]
I vote this
<img width="587" alt="screen shot 2016-05-03 at 1 51 32 pm" src="https://cloud.githubusercontent.com/assets/2397765/14997977/46c3e162-1136-11e6-824b-db7bacf7306e.png">

**Comment by kcjonson** [comment]
I'm leaning towards having red in the color as a hat tip to Redfin.  That said, I like the "slots" graphic element a bit more than just "dots"

**Comment by roblg** [comment]
+1 on "slots" as opposed to "dots".

I like that the rounded squares look kind of like floppy disks, even though I'm sure that that is not how they were intended. :)

I like the Redfin red scheme, but I also like how futuristic-looking the blue react atom on gray floppy disk w/ slots looks.

(Disclaimer: I am not a designer.)

**Comment by helenaut** [comment]
I don't like the red and grey because the dot and stuff reminds me too much
of Reddit

**Comment by jmhwang7** [comment]
@helenaut What if we don't have dots. Just solid layers? I like that. It's simple and elegant.

**Comment by careylin** [comment]
<img width="1420" alt="slots n stuff" src="https://cloud.githubusercontent.com/assets/8015761/15004020/9b7eff04-1166-11e6-9812-9aa01bd39e58.png">

**Comment by gigabo** [comment]
:drool:

**Comment by dfabulich** [comment]
A1 or C1, I think. C1 reminds me of the Nintendo Entertainment System, for what that's worth.

**Comment by doug-wade** [comment]
fixed in #133
