### ISSUE TITLE
Pass in the token to be replaced in the module tagger

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#12]
Something like:

```javascript
var tagger = require("react-server-gulp-module-tagger");
...
gulp.src(...).pipe(tagger("__LOGGER__"));
```

**Comment by doug-wade** [comment]
To allow using different tokens in client code, rather than __LOGGER__?  And we should def keep the current values as defaults so that you can still `.pipe(tagger())`

**Comment by doug-wade** [comment]
This is now possible with the babel plugin, but I think we should leave the issue until we support it in the gulp plugin as well.
