### ISSUE TITLE
reuseDom Client Transition error

### ISSUE THREAD

**Issue by nampas** [redfin/react-server#127]
I ran into an issue today with reuseDom, when the destination page has fewer root elements than the source page.

Let's say Page A has 3 root elements, Page B has 1 root element.
When transitioning from from page A to page B via a Client Transition with reuseDom, the 1st root element will get correctly replaced by Page B, but the 2nd and 3rd root elements will remain unchanged (minus CSS) from Page A.

reuseDom needs to wipe out extra root elements when transitioning to a page with fewer Root Elements. 

Unfortunately I don't have a good, non-sensitive test case for this.

**Comment by gigabo** [comment]
Nice catch @nampas!  Thanks for reporting!
