### ISSUE TITLE
Add a "writing a page" doc

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#129]
We have "writing middleware" and "page API", but no overview of writing a page.

Worth highlighting:
- Methods have sane defaults
- Data requests should be kicked off in `handleRoute`
- Importance of `getAboveTheFoldCount`
- ???

**Comment by TonyHYK** [comment]
maybe also
- optimizing on TTFB by making sure that things in the header (e.g. getTitle, getMetaTags, and getLinkTags) are as light-weight as possible

**Comment by gigabo** [comment]
Nice, good idea @TonyHYK.
