### ISSUE TITLE
RootContainers count twice for getAboveTheFoldCount

### ISSUE THREAD

**Issue by lidawang** [redfin/react-server#144]
We have a page that has an entire `RootContainer` that's above the fold, but we don't account for it in our `getAboveTheFoldCount` implementation. While debugging why our waterfall is looking weird (caused by this wrong count number), we noticed that the fix would be to a) take into account the `RootContainer` in our `getAboveTheFoldCount` implementation, but also b) increment our count by 2 for each entirely-above-the-fold `RootContainer`. The latter is extremely confusing and easy to miss - can we either omit `RootContainer`s from being part of the above-the-fold-count (they are elements, but they're container elements that can only contain `RootElements`, which already count for above-the-fold so it seems duplicative), or at least fixing this double-counting thing?

**Comment by gigabo** [comment]
Thanks for reporting @lidawang.  That's definitely confusing.  I think omitting `RootContainer`s entirely from the above-the-fold count makes the most sense.

**Comment by gigabo** [comment]
Good bug @lidawang.  @bartkusa came up with a better API that doesn't have this sort of confusing behavior to deal with.  We're going to migrate to that, so closing this ticket as not relevant to _the future_.
