### ISSUE TITLE
Replace __reactServerTimingStart with browser's navigation start event

### ISSUE THREAD

**Issue by TonyHYK** [redfin/react-server#145]
React-server writes out a script tag as early as possible in the head to log t0 on the client side. Now that navigation timing API is available in all the browsers we care about, we get to eliminate this script tag and call into the browser's (presumably more accurate) t0 via `window.performance.timing.navigationStart`

**Comment by gigabo** [comment]
Nice!  That will be a good improvement.  Thanks @TonyHYK!

Feel like taking it on? ;)

**Comment by TonyHYK** [comment]
yup I will take it!

**Comment by TonyHYK** [comment]
Closing issue as this is addressed in this PR: https://github.com/redfin/react-server/pull/148
