### ISSUE TITLE
Travis CI build is broken

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#15]
Failing on [`lerna bootstrap`](https://travis-ci.org/redfin/react-server/builds/108697795#L665).  Not sure why, exactly.  Works locally.  Worked pre-`lerna publish` of `v0.0.6`.

Only thing I can think of is the cross-dependency version didn't get updated during publish.

Filed [a ticket](https://github.com/kittens/lerna/issues/50) on lerna about the unexpected publish behavior.

Meanwhile, maybe we should just update the cross-dependency version manually?

**Comment by gigabo** [comment]
"Fixed" by https://github.com/redfin/react-server/commit/35f7a71c430a71b9618ae00b61ccfcc1446619bd.

**Comment by gigabo** [comment]
Horked again.  `lerna bootstrap` just isn't `npm link`ing on Travis?  Is that what's happening?

**Comment by dtothefp** [comment]
@gigabo did you ever get this figured out, my `lerna bootstrap` in a module I'm creating completes but fails to link the packages. Wonder if you have some insight?

<img width="1062" alt="screen shot 2016-03-18 at 1 45 22 pm" src="https://cloud.githubusercontent.com/assets/4656726/13887397/e10c0d60-ed11-11e5-8cb4-e5e5810f25c3.png">

**Comment by gigabo** [comment]
@dtothefp Nope, we've just been working around it by updating versions manually.

**Comment by dtothefp** [comment]
@gigabo so this is happening to me when only one package updates, and it isn't `boiler-utils` so the version should be correct in the package.json of the updated dependency. I'm a little unclear about what is actually happening here?

**Comment by gigabo** [comment]
This was resolved by upgrading to `lerna@v2.0.0-beta.5`.
