### ISSUE TITLE
Better API for declaring the fold: <TheFold />

### ISSUE THREAD

**Issue by bartkusa** [redfin/react-server#161]
Instead of saying "the fold for this page is after the first N elements" (which could change based on middlewares? maybe?), it'd be nice if you could just declare it inline with everything else in JSX. Eg:

```
getElements() {
	var prefetchConfig = {prefetchUrls:this._getPrefetchURLS()};
	
	return [
		RootElements.createRootElementWhenResolved(this._emailVerificationBannerStore, <EmailVerificationBanner />),
		RootElements.createRootElementWhenResolved(this._searchAndMerchStore, <SearchAndMerch />),
		<TheFold />
		RootElements.createRootElementWhenResolved(this._listingFeeStore, <MarketingSections />),
		RootElements.createRootElementWhenResolved(this._generalInquiryStore, <GeneralInquiryForm />),
		RootElements.createRootElementWhenResolved(this._eigencitiesStore, <EigencitiesSection />),
		<Prefetch {...prefetchConfig}/>,
	];
}
```

(Obviously it doesn't need to _really_ be React or JSX. It could just be `require("react-server/TheFold")` or something.)

**Comment by gigabo** [comment]
@bartkusa - That's an awesome idea!  _SO_ much better than the current API!

**Comment by lidawang** [comment]
This change would make life sooo much easier for the DP!
