### ISSUE TITLE
Implement getCanonicalUrl

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#167]
From https://github.com/redfin/react-server/pull/166, we plan to implement the following page api method

`getCanonicalUrl(next: Function), optional: String | Promise(String)`

* **NOT YET IMPLEMENTED**
 
* A string (or promise thereof) that is the canonical URL for this webpage
 
* Default: no canonical URL header added.

**Comment by gigabo** [comment]
Isn't this covered by `getLinkTags()`?

Is there any other use of the canonical URL beyond adding a `<link rel="canonical" ...>` tag?

**Comment by aickin** [comment]
As someone who probably wrote/might have written/vaguely remembers writing that function prototype, I think that `getLinkTags` is enough and don't think it's worthwhile to have a specific `getCanonicalUrl` method.

**Comment by gigabo** [comment]
Sweet.  Thanks @aickin.
