### ISSUE TITLE
Add a "running in production" doc

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#188]
It's [not clear](https://github.com/redfin/react-server/issues/185) from our current documentation how this is supposed to work.

**Comment by doug-wade** [comment]
We spent some time talking about `pm2` in [slack today](https://react-server.slack.com/archives/discussion/p1471405319000502) and discovered that you should use `pm2 start npm --watch --ignore-watch="__clientTemp" -- start`, given `"scripts": { "start": "react-server start"}` in your package.json, which seems like worth adding to this doc (once we have it 😀 )

**Comment by doug-wade** [comment]
This was fixed in #777; closing
