### ISSUE TITLE
Add support for custom webpack loaders

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#199]
From [reddit](https://www.reddit.com/r/reactjs/comments/4k5uer/react_server_blazing_fast_page_load_and_seamless/d3e3gfh):

> How do I use my own webpack loaders? i.e. I'd like to use CSS modules, maybe I have a markdown loader, etc.

We don't have a good answer to that with `react-server-cli` yet.  Maybe via `.reactserverrc`?

**Comment by tsnieman** [comment]
Some freeflow thoughts to help get the conversation started:
- Imagining something like `routes` config (either CLI or `.reactserverrc`) where you can point it to a `webpack.config` file. Then you have the problem of **loader ordering** - are the configured loaders from the end-user's webpack used BEFORE the ones provided by `react-server`? Maybe there's concepts like `afterBabelLoader `or `afterServerLoaders`? Seems a bit funky..
- Loaders might cause some issues if they're not isomorphic-friendly, I imagine. (I also haven't tried something that uses `window` yet but curious to see how `react-server` handles it)

I'll definitely be poking through the source soon to see if there's anything I can help do to improve this issue, as it's probably the only thing really holding me back from using `react-server`.

**Comment by gigabo** [comment]
Yeah it would be tough to automatically merge a whole `webpack.config`, though maybe [`webpack-merge`](https://www.npmjs.com/package/webpack-merge) could help?  Targeted `afterBabelLoader`-type hooks might be easier to tame, but I wonder how many of them we'd eventually wind up with...

Thanks for looking at this @tsnieman!

**Comment by CreepGin** [comment]
Agree with the complexity involved with custom webpack configuration. But in the case of CSS Modules, we can _safely_ _consider_ enabling it by default.

**Comment by gigabo** [comment]
I think #598 took care of this (and #709 added a CLI option for it). 🎉
