### ISSUE TITLE
Move chat to slack?

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#201]
I really prefer slack over gitter.  Noticed that lerna's on slack.  Now I'm jealous.

I propose we move the public chat to slack.

Pros:
- Can have multiple channels (announcement/discussion/development/...)
- Can have _private_ channels (e.g. contributors)
- Can do non-spammy reactions.  Seems trivial, but actually useful (e.g. vote-style up/down)
- Handy for those of us who are _already_ on slack all day
- Generally more polished.  They've got the $$$.

Cons:
- No github SSO.  A new account for a lot of people
- _Most_ github projects seem to be on gitter, so it's probably more familiar to a lot of people
- Limited message history on the free tier
- We're _already_ on gitter, so there's some work involved in moving

For me the pros outweigh the cons.  Thoughts?  Opinions?

**Comment by doug-wade** [comment]
I love Slack, and I'm totally in favor of moving to it, but I think we need a solution that has open registration, or a way for new users to "let themselves in" to the chat, and iirc, Slack doesn't have that.  How do new users that want to ask a quick question get access to our Slack channel?

**Comment by mattiasewers** [comment]
How about discord?

**Comment by gigabo** [comment]
Looks pretty easy to set up [slackin](https://github.com/rauchg/slackin) for slack auto-registration.

**Comment by gigabo** [comment]
@mattiasewers - Yeah, there are a few other potentially good chat setups out there.  Given the market dominance of slack (and my personal bias 👹 ), though, I'd be hesitant to jump from gitter for anything less.

**Comment by mattiasewers** [comment]
@gigabo yes you're right, but discord is probably easier for new users to join.

**Comment by jamen** [comment]
I've used both Slack and Discord for a good amount of time, and I still like Slack a lot and would prefer it.  It's just unfortunate they're not more open to the community aspect of things.  But as @gigabo mentioned, there are things like Slackin that make it really easy.

**Comment by gigabo** [comment]
@mattiasewers - Yeah, that's a real concern.  I hadn't realized that lerna was using a custom registration setup.

Like @doug-wade said, though, it's really easy to auto-register for their slack org!

If all we need is to set up a host running [this](https://github.com/rauchg/slackin#custom) somewhere, that's not a huge barrier.

```bash
$ npm install -g slackin
$ slackin "your-team-id" "your-slack-token"
```

**Comment by gigabo** [comment]
Huh.  Looks like [babel's on slack](https://github.com/babel/babel#looking-for-support), too.

**Comment by egid** [comment]
I helped set up slackin for another project. It's been solid.

The only downside, imo, is that popular projects on free plans start losing access to message history _very_ quickly.

**Comment by aickin** [comment]
> Noticed your vote on the 👎 side. Anything to add to the "cons" list?

Nope, I think you pretty much summed it up. Please see it as a weakly held 👎; I don't care that much and am happy to do what others decide.

**Comment by hairthing** [comment]
@gigabo FYI your quoted thumbs down got counted as a vote
