### ISSUE TITLE
We need a changelog

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#202]
I just published `0.2.12`.  What was in it?  Who knows?!

We need to start communicating what's happening from release to release.

A few options:

- I'd really like to use [`lerna changelog`](https://github.com/lerna/lerna/pull/29) but it sounds like that might actually never land.  It _could_ be pulled out into a dedicated tool.
- Looked at [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog).  It's pretty tied to a squash-merge workflow, which doesn't mesh with what we've got going on here.
- Could always just manage a changelog by hand, but... \*_shudder_\*

**Comment by gigabo** [comment]
Tried out `conventional-changelog`.  It produced a totally empty changelog.  Empty items for each release tag.  Not helpful.

**Comment by doug-wade** [comment]
Seems like we'd have to use something like [commitizen](https://github.com/commitizen/cz-cli) to enforce commit messages to make `conventional-changelog` work.

Just searching about for a quick second turns up [this](https://skywinder.github.io/github-changelog-generator/) ?

**Comment by gigabo** [comment]
@doug-wade - That second one looks like a ruby version of @hzoo's [changelog generator](https://github.com/lerna/lerna/pull/29/files) for babel.

@hzoo - That seems pretty self contained.  Would you be interested in spinning it off as a stand-alone tool?

**Comment by hzoo** [comment]
We could publish a specific release of lerna with it as a workaround with that isn't a prelease/normal version based on 2.x since that would be the least work. Yeah I'm ok with making it standalone too

**Comment by gigabo** [comment]
@hzoo - It's the closest thing to an it-just-works solution for us.

But I've got a laundry list of changes I'd like to make to it, too:

- Configurable tags
- Tag => heading mapping (`toTitleCase(tag.slice(5))` doesn't work for ours that aren't `tag: ` prefixed)
- API response caching.  Requests are the same each time I run with a tweaked configuration.
- Skip changes to files in `publishConfig.ignore`.  Don't need to include `README` updates, etc.

It's not _tied_ to lerna, in that it doesn't really depend on it (though it would for `publishConfig.ignore`), but it's really meant for use on lerna repos.  Seems to make the most sense as a lerna command, but it sounds like there isn't a path to get it merged in?

I don't want to maintain a fork of `lerna` with my changes to `lerna changelog`.

**Comment by gigabo** [comment]
We've got [a changelog in `next`](https://github.com/redfin/react-server/blob/next/CHANGELOG.md) now.  Generated using [`lerna-changelog`](https://github.com/lerna/lerna-changelog).
