### ISSUE TITLE
Generate `.reactserverrc` with `yo react-server`

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#203]
I think the generator predates the config file.  Seems like it should make one.

**Comment by withinboredom** [comment]
What specifically should be generated in the default? Def want to have a default docker env setup ... Would make sense for a generic staging/prod, maybe a local env too?

**Comment by gigabo** [comment]
Yeah, that sounds good.

Would it make sense just to populate with all the defaults so it's clear how to override?
