### ISSUE TITLE
Bad Link to redfin.github.io/react-server

### ISSUE THREAD

**Issue by winkler1** [redfin/react-server#223]
![image](https://cloud.githubusercontent.com/assets/883896/15580612/533ec84a-2337-11e6-8447-128a402517bb.png)

**Comment by gigabo** [comment]
Thanks for reporting @winkler1.  Not sure what happened there.

Maybe someone was testing something? @doug-wade?

Anyway, looks like it's gone, now.

**Comment by winkler1** [comment]
@gigabo hmm, seems to still be happening here-
![image](https://cloud.githubusercontent.com/assets/883896/15587558/cc6ffa34-2357-11e6-8342-661d9597a7e6.png)

**Comment by doug-wade** [comment]
I uh... wat

<img width="1440" alt="screen shot 2016-05-26 at 12 40 01 pm" src="https://cloud.githubusercontent.com/assets/3477707/15587666/21221f1c-233f-11e6-8356-ee4bca2984b3.png">

**Comment by doug-wade** [comment]
Not in incognito mode either?!?
<img width="1440" alt="screen shot 2016-05-26 at 12 42 03 pm" src="https://cloud.githubusercontent.com/assets/3477707/15587714/504757da-233f-11e6-819b-2d473547db2c.png">

**Comment by winkler1** [comment]
@doug-wade Looks like caching strangeness from Github. Looks fine in Firefox also. See updated screenshot above where two chrome windows show different results!
thx

**Comment by doug-wade** [comment]
![what is going on](https://d.gr-assets.com/hostedimages/1457545577ra/18373085.gif)

**Comment by doug-wade** [comment]
weird. huh.
