### ISSUE TITLE
Handle web font files

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#233]
Webpack chokes on them without a loader, and the asset servers don't know what to do with them.

Can they be handled in user space with smarter asset servers and [custom loader support](https://github.com/redfin/react-server/issues/199)?

Do we need to bake in handling for webfonts (and all future asset types)?

Need to do _something_.

Born from #227.

**Comment by gigabo** [comment]
@withinboredom - You interested in looking at this?

**Comment by aickin** [comment]
FYI, I'm working on the quick and dirty solution in a branch. Hopefully a PR within a few days, depending on other commitments.

**Comment by gigabo** [comment]
Awesome.  Thanks @aickin!

**Comment by aickin** [comment]
I believe this should be closed now that #251 is merged. 

Might be worth opening a bug for more generically applicable file handling, but the use case for this bug is fixed, I think.

**Comment by gigabo** [comment]
Oh, yep!  Thanks @aickin.
