### ISSUE TITLE
Add support for streaming rendering

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#244]
> I also had to put this in, as I wrote react-dom-stream; probably also not a particularly good use of time right now until rds is a bit more stable.

Migrated from #50

**Comment by aickin** [comment]
FYI, I'm trying to get streaming in to react core in https://github.com/facebook/react/pull/6618 and https://github.com/facebook/react/pull/6836 . I think we shouldn't work on this until it's in core (or they reject the PRs).

**Comment by drewpc** [comment]
@aickin Are you still working this on the React core side?  Both of the mentioned PRs look outdated and have merge conflicts.

**Comment by aickin** [comment]
@drewpc Sigh... I think the PRs are dead, and we should probably close this too, as I haven't updated the core react-dom-stream to React 15.

I'm still looking at how to do this with Fiber (the upcoming React architecture), and hope to have some convos with the core team in the coming weeks.

But in the meantime, I'd just close this issue as WONTFIX.

**Comment by drewpc** [comment]
Okay, thanks for the update.
