### ISSUE TITLE
Simplify the use of routr

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#245]
> Routr could be a little more user friendly if it had some smart defaults. For instance, it'd be nice if it didn't require you to always specify the HTTP method of every route, but rather just assumed GET.

Migrated from #50

**Comment by aickin** [comment]
I think that this may be fixed by https://github.com/redfin/react-server/pull/100

**Comment by gigabo** [comment]
Oh, yep.  Thanks.
