### ISSUE TITLE
react-server-cli doesn't hot reload or watch components that require react-server-gulp-module-tagger

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#247]
When working on #222, I had to take down the server and restart it every time I changed a component because I used the logger, and that requires tagging, which react-server-cli doesn't do.  We should either switch from using gulp to using a [babel plugin](https://babeljs.io/docs/plugins/) for our source transforms, or we could update react-server-cli to use react-server-gulp-module-tagger as part of its compile step.

**Comment by gigabo** [comment]
> update react-server-cli to use react-server-gulp-module-tagger as part of its compile step

I totally thought it did that.
