### ISSUE TITLE
`gulp test` output is noisy

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#26]
There are at least three sources of noise in `gulp test` output:
- Excess `gulp-chug` prefixes
  - Addressed by https://github.com/robatron/gulp-chug/pull/22 but not yet published.
- Node's `(node) OutgoingMessage.flush is deprecated. Use flushHeaders instead` warning.
  - Could be addressed by https://github.com/expressjs/compression/pull/74.  Pending review.
- `Error in renderPage chain message=Timed out rendering.`
  - This is just a `logger.error()` message.  We should capture and suppress.

**Comment by gigabo** [comment]
![image](https://cloud.githubusercontent.com/assets/115908/13128665/4ba30568-d58c-11e5-8687-e8220ec2e26a.png)

:scream:

**Comment by doug-wade** [comment]
This was resolved in https://github.com/redfin/react-server/pull/113, imo

**Comment by gigabo** [comment]
This still bugs me:

```
.........................................................[object Object]
..[object Object]
.[object Object]
..........................................................
```

**Comment by drewpc** [comment]
This is no longer noisy.
