### ISSUE TITLE
Test servers hang during cleanup

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#262]
Repro:

```bash
$ cd packages/react-server-integration-tests
$ npm test
```

After the tests complete the process doesn't exit immediately.  Maybe something in test server teardown?

![image](https://cloud.githubusercontent.com/assets/115908/15789116/792c360c-297f-11e6-9e74-f572059d07a0.png)

Seems to [cause travis build times to fluctuate](https://github.com/redfin/react-server/pull/258#issuecomment-223653737).

**Comment by aickin** [comment]
To be clear for whoever works on this: the tests usually pause for a ton of time (minutes!) after the specs are all finished but before the gulp task exits, but to my knowledge they don't just hang _forever_.

**Comment by gigabo** [comment]
Oops, the screen shot in the description left out some key info. 😆 

![image](https://cloud.githubusercontent.com/assets/115908/15789252/09d7e05c-2980-11e6-8812-93314385050d.png)

**Comment by doug-wade** [comment]
Not sure if this is the right place to add this, but we can track our overall build time with [this here graph](http://scribu.github.io/travis-stats/#redfin/react-server)
