### ISSUE TITLE
Use `add-module-exports` babel plugin to reduce `*.default`

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#285]
These have been creeping into common.js, especially.  Seems simple to eliminate?

https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by karanjthakkar** [comment]
@gigabo I was looking into this and think I can help. Is this something that you want only in the `react-server` package or throughout all packages?

**Comment by gigabo** [comment]
Hi @karanjthakkar thanks for taking this on!

Yeah, I think `react-server` is the biggest offender.

Looks like `react-server-core-middleware` has a couple, too.

**Comment by karanjthakkar** [comment]
@gigabo I've set it up locally but running into this issue on my local machine: https://github.com/redfin/react-server/issues/292 on node 4.2.3. Trying it out now with the latest node.
