### ISSUE TITLE
Yeoman generator fails with defaults if directory has a dash

### ISSUE THREAD

**Issue by aickin** [redfin/react-server#290]
To repro, assuming you have `yo` and `generator-react-server` globally installed:

1. `mkdir my-dir`
1. `cd my-dir`
1. `yo react-server`
1. Accept all defaults

The name that it suggests for the project as a default will be "my dir". But when yo attempts to call `npm install`, that will fail, as you can't have spaces in a project name.

Expected: it uses the `my-dir` as the default project name.

**Comment by gigabo** [comment]
Yikes.  Nice catch, @aickin. 😬
