### ISSUE TITLE
Requests other than "get" is not working

### ISSUE THREAD

**Issue by mattiasewers** [redfin/react-server#312]
When setting `method:  'post` and trying to make post request to a the route I get `Cannot POST /foo`. Looked in the docs and didn't find if any config is needed for this.

**Comment by gigabo** [comment]
Oh, yeah... we actually have an _old_ ticket open for that internally from before we even open-sourced `react-server`...

As a workaround you can actually just leave it `method: "get"` and it will accept `POST` requests. 😬 

Thanks for reporting @mattiasewers.  Good to have that tracked here.

**Comment by mattiasewers** [comment]
@gigabo ahh I see, cool. Another thing, how do I get the payload sent with the request? `this.getRequest().getBody()` returns `undefined`, although I get the data in the config object return from the request....weird

**Comment by gigabo** [comment]
Ah, yeah.  We use the [`body-parser`](https://github.com/expressjs/body-parser) express middleware internally.  #249 is open to add that to the server set up by `react-server-cli`.  Should be a straightforward patch.

**Comment by mattiasewers** [comment]
@gigabo ok I got it working, I could make a PR?

**Comment by gigabo** [comment]
Nice! Please do!

**Comment by drewpc** [comment]
Solving this issue and addressing the [breaking changes](https://github.com/yahoo/routr/blob/master/CHANGELOG.md#breaking-changes-1) when upgrading `routr` from 0.1.3 to >1.0 need to be addressed prior to the next release.

**Comment by drewpc** [comment]
Fixed!
