### ISSUE TITLE
Add a favicon to the documentation site

### ISSUE THREAD

**Issue by davidalber** [redfin/react-server#447]
The documentation site needs a favicon. It currently looks like this in my browser:

![image](https://cloud.githubusercontent.com/assets/933552/17126919/6d627a56-52b6-11e6-84c0-117efddb2d7f.png)

**Comment by davidalber** [comment]
How obsessive do we want to be with this? Take a look at [this](https://github.com/audreyr/favicon-cheat-sheet#the-images) and consider the answer.

**Comment by gigabo** [comment]
Wow, that's a great resource!

Maybe we could start with these?

![image](https://cloud.githubusercontent.com/assets/115908/17375061/4bba1f26-5964-11e6-998f-de032299d985.png)

**Comment by doug-wade** [comment]
There's a "every damn size, sir!" button on this page that seems promising: http://www.favicomatic.com/

**Comment by gigabo** [comment]
This is done.  Thanks @davidalber!

![image](https://cloud.githubusercontent.com/assets/115908/20776749/5f199c5c-b717-11e6-97ec-2e6aee52b1b4.png)
