### ISSUE TITLE
Need compression on the website

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#491]
Can we just enable the nginx equivalent of `mod_deflate`?

Google page speed tool is complaining about uncompressed JS bundles.

![image](https://cloud.githubusercontent.com/assets/115908/17349465/c925617e-58d2-11e6-9b27-f83e1de8f94b.png)

**Comment by davidalber** [comment]
Relevant information:
- http://nginx.org/en/docs/http/ngx_http_gzip_module.html
- https://www.nginx.com/resources/admin-guide/compression-and-decompression/

**Comment by patrick-mcdougle** [comment]
I don't think this was fixed by #494 (at least in the HTML case) It'd be swell if each of the RootElements were gzipped before transport. Is this possible?

**Comment by gigabo** [comment]
Hmmm... dev tools are showing that the html response is compressed, at least for the homepage:

![image](https://cloud.githubusercontent.com/assets/115908/17902806/ae8f3aa0-691d-11e6-9ba3-6208a2a17ded.png)


@patrick-mcdougle - Which page are you seeing uncompressed HTML on?

**Comment by patrick-mcdougle** [comment]
@gigabo you've got a content length header there. That means that the whole payload must have fit and the response wasn't chunked at all, but it doesn't matter because it doesn't look like there's any issue. Sorry for the false alarm.

**Comment by gigabo** [comment]
Ooh, nice catch!

We're using nginx as a caching reverse proxy and letting it handle encoding.  Looks like it's being smart about un-chunking response bodies that fit in the window.

Here's a longer one that it leaves chunked:

https://react-server.io/docs/intro/why-react-server
![image](https://cloud.githubusercontent.com/assets/115908/17912851/3f5de02c-694b-11e6-968f-3a6b242beb35.png)

Hadn't realized it was doing that.  Nice little optimization. :)

**Comment by gigabo** [comment]
Oh, actually... maybe we should reduce the window size.

@davidalber Is that configurable with nginx?

Here's what we do at Redfin:

```javascript
        if (gzipEnabled) {
                // The default value for `windowBits` is 15 (32K).  This is too
                // large for our CSS/script includes to make it through before
                // we start waiting for the body.  We _really_ want to kick off
                // secondary resource requests as early as possible, so we'll
                // decrease the window size to 8K.
                //
                // TODO: allow gzip opts to be specified via config?
                server.use(require('compression')({ windowBits: 13 }));
        }
```

Or, rather, what we _used_ to do before we offloaded encoding to nginx internally.

Maybe we should look at tuning that again on redfin.com, too. 😁

**Comment by patrick-mcdougle** [comment]
If you end up needing to change anything, please tell!

**Comment by davidalber** [comment]
> @davidalber Is that configurable with nginx?
If it is, it isn't immediately obvious, but I don't yet believe that it's not configurable.
