### ISSUE TITLE
Let's Encrypt is really slow?

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#492]
What is this I don't even.

http://www.webpagetest.org/result/160803_9J_127/

![image](https://cloud.githubusercontent.com/assets/115908/17349539/94148126-58d3-11e6-8c05-7c7ebde98364.png)

Consistent results (three in a row).

**Comment by gigabo** [comment]
Doesn't repro on Chrome. :feelsgood: 

http://www.webpagetest.org/result/160803_7X_140/

**Comment by davidalber** [comment]
Here you go: https://community.letsencrypt.org/t/ocsp-requests-to-identrust-com-slow/16992.

Here's their ticket for it (now closed): https://github.com/letsencrypt/boulder/issues/1929.

**Comment by davidalber** [comment]
I've switched us to use [AWS ACM](https://aws.amazon.com/certificate-manager/), not really due to this issue, but because it simplifies our setup. As a result, this issue no longer impacts us.
