### ISSUE TITLE
Navigation event for Analytics

### ISSUE THREAD

**Issue by nancydo** [redfin/react-server#502]
Create a navigation event that fires as soon as page title is set.

**Comment by gigabo** [comment]
Talked with Nancy about this offline.  Currently there's no event that fires consistently across all navigation types (page load, client transition, frameback, ...) until `loadComplete`.  That's pretty late to fire a pageload event for analytics.  There may be other analytics events that fire _before_ that which may wind up associated with the wrong page.

So, this will be an event that fires consistently as soon as the data for an analytics page view event (url, title, navigation type) is ready.

Thanks for filing @nancydo.
