### ISSUE TITLE
Express alternative

### ISSUE THREAD

**Issue by DylanPiercey** [redfin/react-server#547]
For the past couple years I have been working on [Rill](https://github.com/rill-js/rill) as an isomorphic/universal alternative to Express/Koa.

I figured i'd share it with you guys since it seems like an interesting fit for this library.
It has [initial render state transfer](https://github.com/rill-js/session), [isomorphic rendering](https://github.com/rill-js/react) and middleware built in.

I'd be willing to play around with swapping out express if any one is was interested.
Feel free to close this issue, good work on the project by the way 😄.

**Comment by doug-wade** [comment]
See also #235

**Comment by DylanPiercey** [comment]
@doug-wade, thanks for the link.
Would be good to support all frameworks for sure, didn't realize this was in progress.

Let me know if you are still at all interested in integrating Rill though, I think it would be of of good use for the client side of things.

**Comment by DylanPiercey** [comment]
Gonna close this since the discussion is in #235
