### ISSUE TITLE
Heroku support?

### ISSUE THREAD

**Issue by littletower** [redfin/react-server#566]
Hi,

Has anyone tried to run this on Heroku (or similar)?

Did have time to test it myself, just curious :)

Amazing project by the way!

**Comment by doug-wade** [comment]
I've run them on ec2 instances, but never heroku.  Heroku's pretty easy to use, and pretty platform-agnostic -- I've run other Express-based apps on them before -- so I'd be surprised to discover there are an gotchas lurking.  Is there something in particular you're worried about?

**Comment by littletower** [comment]
thanks @doug-wade 
I was just wondering if anyone had tried it, since I really don't have enough time at the moment. I've see other react projects with deployment issues on Heroku, but I don't think they were Express-based. So like you said, there probably should not be any issues :)
I'll let you know once I've tried!

**Comment by hzhu** [comment]
@littletower I just got my first deploy of react-server on Heroku. It requires only a one liner in a Procfile. You can see the app [here](https://react-server-redux.herokuapp.com/).

I am however getting these log errors from the JS assets server:
```
(index):6 Mixed Content: The page at 'https://react-server-redux.herokuapp.com/' was loaded over HTTPS, but requested an insecure script 'http://localhost:3001/common.b3f98eeedb50d3031abd.bundle.js'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ (index):6P @ (index):6S @ (index):6(anonymous function) @ (index):6script @ (index):6(anonymous function) @ (index):7
(index):6 Mixed Content: The page at 'https://react-server-redux.herokuapp.com/' was loaded over HTTPS, but requested an insecure script 'http://localhost:3001/HomePage.7cdf21b5a5bf0911d1f3.bundle.js'. This request has been blocked; the content must be served over HTTPS.(anonymous function) @ (index):6P @ (index):6S @ (index):6(anonymous function) @ (index):6script @ (index):6(anonymous function) @ (index):7
```

@doug-wade I don't know much about the 3001 server. I know a custom port could be passed in on as an argument in the CLI but it's weird that Heroku starts it on "localhost". Have you  ran into this issue in EC2?

**Comment by littletower** [comment]
@hzhu thanks a lot! I really need to give it a try now 🎉

**Comment by doug-wade** [comment]
@hzhu We have been seeing some problems with [the static asset server and secure connections](https://react-server.slack.com/archives/discussion/p1472252040000870) recently -- the wrong URL is being passed to the loading middleware.

**Comment by hzhu** [comment]
@doug-wade thx for the link to the chat, shall we post a separate GitHub issue for that?

**Comment by doug-wade** [comment]
@hzhu yeah go ahead and file it.  I haven't had a chance to take a look at it -- the fire's burning pretty hot here at Redfin -- but hopefully I can get to it by EOW

**Comment by hzhu** [comment]
@doug-wade no worries, I'll file that. Ya'll are doing a wonderful job btw. Thanks a bunch.

**Comment by eduardoboucas** [comment]
Any movements on this? Just deployed the app to Heroku and I'm getting the Mixed Content errors as well.

Thanks!

**Comment by stanleycyang** [comment]
Yeah looks like the URLs for the assets are pointing to the wrong place.

**Comment by drewpc** [comment]
[This line in the code](https://github.com/redfin/react-server/blob/master/packages/react-server-cli/src/run.js#L33) shows where the problem is.  It seems like there's not really a good way to work around this without a change to `react-server` because of the http vs https check on that line.  One change might me modifying the offending line to look like this:

```
options.outputUrl = jsUrl || `//${host}:${jsPort}/`;
```

Another option for changing this would be to consolidate the HTML and JS servers as described in #807.

Additionally, you would need to change your `host` parameter to be `0.0.0.0` so that the Javascript loader pulled the JS/CSS files from the browser location instead of hardcoding to `localhost`.
