### ISSUE TITLE
Autoreload not working

### ISSUE THREAD

**Issue by alex88** [redfin/react-server#578]
I've started a new project running the yo generator and started the server, first of all when I replaced the route I had to delete the `__clientTemp` folder, then when I change the getElements content I've to restart the server, i that supposed to work that way?

**Comment by CreepGin** [comment]
Hot reloading only works for changes to components right now. Modifications to routes.js or the page classes still require manual reload. But pm2 can solve that nicely:

```
pm2 start npm --watch --ignore-watch="__clientTemp" -- start
```

**Comment by alex88** [comment]
Ok gotcha, thank you @CreepGin 
Just seen that also hot reloading is not enabled by default in development but I have to add `--hot` in the npm start command

**Comment by mocheng** [comment]
To same late comer's time, I met same problem and managed to find it is the `hot` field in `.reactserverrc` controlling hot-reload. Just set it to be `true` and Hot-Module-Reload is enabled for `npm start`.

Adding `--hot` in the npm start comand doesn't work. I suppose there is some feature change after @alex88 closed this issue.
