### ISSUE TITLE
Invite limit reached at slack.react-server.io

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#580]
[Reported](https://github.com/redfin/react-server/pull/579#issuecomment-240500882) by @alex88.

![image](https://cloud.githubusercontent.com/assets/115908/17748156/ec303aae-646c-11e6-85fb-281bfc91e3bd.png)

**Comment by gigabo** [comment]
Not even allowed to send manual invites. :(

Details: https://get.slack.help/hc/en-us/articles/201330256#invitation_limits

**Comment by gigabo** [comment]
Posting [here](https://react-server.slack.com/help/requests/new):

![image](https://cloud.githubusercontent.com/assets/115908/17748552/ce363bb4-646e-11e6-8bdc-e05cf2e68b07.png)

**Comment by CreepGin** [comment]
My team actually switched to using Discord (from Slack) for customer-facing communications. Other friends also had good experiences with gitter.im

**Comment by gigabo** [comment]
We recently [moved _from_ gitter.im](https://github.com/redfin/react-server/issues/201). :hurtrealbad: 

@CreepGin - What drove you away from slack?  How has discord been in comparison?

**Comment by CreepGin** [comment]
Oh no, we still use slack internally and like it very much. But for our non-developer customers, all of them preferred Discord over slack (just in the field of online chatting) mostly due to:

- Straight-forward Invites
- Simpler UI
- Snappier native clients
- Good localization (we have a lot of international users)

But then again, I just realized that all your customers are developers =(

**Comment by gigabo** [comment]
> all your customers are developers

Yeah, exactly. 😛 

We use slack internally, too, and figured it would work well for React Server.

And it _has_ been working great... until now.

**Comment by CreepGin** [comment]
Though I think even for developers, it should be fine since Discord does have Markdown and code highlighting support.

**Comment by alex88** [comment]
If you need an example, whole react community is there https://facebook.github.io/react/blog/2015/10/19/reactiflux-is-moving-to-discord.html

**Comment by CreepGin** [comment]
Oh another big reason we switched was because Discord doesn't force users to sign up in order to join chat.

@alex88 Oh yes!

**Comment by gigabo** [comment]
Three cheers for Slack support! 🎉 

![image](https://cloud.githubusercontent.com/assets/115908/17750195/e76d6fba-6475-11e6-9b54-0d02621cb6ca.png)

@alex88 - I've sent you a manual invite to the email address in your PR commit message.

Thanks for the link to the facebook post, and the food for thought about discord.  Didn't know it supported markdown and syntax highlighting.

Now that we're back on track with slack invitations I'm hesitant to consider another move, since we _just_ got onto slack, but it's a relief to know there are good alternatives available.
