### ISSUE TITLE
Can't load fonts from css 

### ISSUE THREAD

**Issue by evgeny-matveev** [redfin/react-server#593]
Hello, react-server doesn't load fonts that I've required in my CSS:
```
Font from origin 'http://localhost:3001' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4000' is therefore not allowed access.
```

Example:
```
@font-face{
  font-family: 'Museo Sans';
  src: url('./fonts/museo/MuseoSans700.eot');
  src: url('./fonts/museo/MuseoSans700.eot') format('embedded-opentype'),
  url('./fonts/museo/MuseoSans700.woff2') format('woff2'),
  url('./fonts/museo/MuseoSans700.woff') format('woff'),
  url('./fonts/museo/MuseoSans700.ttf') format('truetype');
  font-weight: 700;
  font-style: normal;
}
```

But I have no problem loading svg (e.g. background-image) in css.

**Comment by gigabo** [comment]
Oooh, interesting... I guess we'll need to set [CORS headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) on the dev webpack server's output?

Thanks for reporting @evgeny-matveev.  I think the only safe solution to unblock your dev process in the short term until we get this patched would be to put a reverse proxy (nginx, apache, ...) in front of your dev servers. 😖 

If you want to live dangerously you could temporarily [relax your browser's CORS enforcement](https://www.thepolyglotdeveloper.com/2014/08/bypass-cors-errors-testing-apis-locally/).

If you're feeling ambitious (and saintly 😇 ) you could look at adding CORS headers with dev server hostname/port to [`startStaticJsServer`](https://github.com/redfin/react-server/blob/master/packages/react-server-cli/src/commands/start.js#L112) and [`startHotLoadJsServer`](https://github.com/redfin/react-server/blob/master/packages/react-server-cli/src/commands/start.js#L155). 😁 

I think that's all it should take to fix this for real.

**Comment by gigabo** [comment]
Wait... the hot load server _has_ an [`Access-Control-Allow-Origin`header](https://github.com/redfin/react-server/blob/master/packages/react-server-cli/src/commands/start.js#L161)! 🎉 

@evgeny-matveev - Could you try running your dev server with `--hot` to see if that clears it up for you?  If so, then it's just a matter of _also_ setting the header on the static development asset server.

**Comment by evgeny-matveev** [comment]
@gigabo Oh, I thought I tried "--hot", but it seems not :( Sorry and thanks!
