### ISSUE TITLE
ReactServerAgent simple GET request forces CORS preflight 

### ISSUE THREAD

**Issue by mpatnode-si** [redfin/react-server#619]
Make a simple GET request via ReactServerAgent and CORS will kick off a OPTIONS preflight.   Make the exact same request directly via SuperAgent and it will work fine.   Best I can tell is that ReactServerAgent is setting Content-Type on the GET request.   Perhaps here?
`
if (this._type && this._type !== 'form-data') {
        req.type(this._type);
}
`

This may be as simply as adding `&& this._method !== 'GET'` but it could be somewhere else as well.

**Comment by mpatnode-si** [comment]
Making the following change to node_modules/react-server/target/client/ReactServerAgent/Request.js Request constructor seemed to do the trick:
`
this._type = (method === "GET") ? "text/plain" : "json"; // Don't force CORS on simple GETs 
`

**Comment by gigabo** [comment]
Nice find @mpatnode-si.

I'm a little confused here, though... Shouldn't `this._type` be `json` for a JSON endpoint?

**Comment by mpatnode-si** [comment]
Well Content-Type in https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html says "indicates the media type of the entity-body sent to the recipient".  Since the GET request typically doesn't contain any JSON, it think "text/plain" is more correct.   On the other hand, most the POST done in this code probably will be JSON, so the default makes sense in that case.

**Comment by mpatnode-si** [comment]
To further complicate matters, it seems the CORS problem is only in the Client code, and my recommend fix actually breaks when executed on the server, so someone smarter than me will need to rectify that.

**Comment by drewpc** [comment]
I have a fix!  Turns out this is the problem: https://github.com/redfin/react-server/blob/master/packages/react-server/core/ReactServerAgent/Request.js#L236
