### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by galkinrost** [redfin/react-server#620]
Hi! I'm trying to include autotrack plugin for ga https://github.com/googleanalytics/autotrack. And react-server expectedly throw error `window is not defined`. Any ideas how to deal with it?

**Comment by galkinrost** [comment]
Solved:

`      
handleRoute() {
  if(typeof window !== `undefined`){
       require('autotrack/lib/plugins/outbound-link-tracker')
  }
...
}
`

**Comment by gigabo** [comment]
Oh, glad you got it working @galkinrost!  Sorry this fell through the cracks yesterday.
