### ISSUE TITLE
Wait for multiple promises to resolve in RootElement

### ISSUE THREAD

**Issue by stanonyime** [redfin/react-server#666]
Thank you for this awesome library. 
Can I do something like:
```javascript
<RootElement key={1} when={this.books && this.authors} >
	<BookList />
</RootElement>
```
When I tried something like that, I only got the props for **authors** in the <BookList /> component and no books. Or am I missing something really obvious?

**Comment by SeverS** [comment]
Hello, 

Assuming that `this.books` and `this.authors` are promises,  you can do `when={ Promise.all([ this.books, this.authors]) }`.

**Comment by gigabo** [comment]
Hi @stanonyime that's a good question!

The code you tried above actually just resolves to `when={this.authors}` if `this.books` is truthy.  It's equivalent to `when={this.books ? this.authors : this.books}`.

@SeverS is on the right track for merging two promises, but there's actually one extra bit that's necessary: Merging the objects that each promise resolves with.

Something like this should work:

```javascript
function mergePromises(...promises) {
  return Promise.all(promises)
    .then(resolutions => Object.assign.apply({}, resolutions));
}

...

<RootElement key={1} when={mergePromises(this.books, this.authors)} >
    <BookList />
</RootElement>
```

That obviously assumes you have access to `Object.assign`, which isn't broadly supported, but an implementation with lodash or just manual merging wouldn't be hard.

Something like that might be nice to make available as a helper exported from React Server...

**Comment by stanonyime** [comment]
Ok. I thanks you all.
