### ISSUE TITLE
Undefined is not a function error in Hello World example browser console

### ISSUE THREAD

**Issue by royagasthyan** [redfin/react-server#674]
On running the hello world example app, in browser console I see the following error 

`error: [react-server.core.ClientController] Error with element render 0 TypeErrormessage: "undefined is not a function"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }proto: Error`

**Comment by doug-wade** [comment]
Closing as a duplicate of https://github.com/redfin/react-server/issues/672
