### ISSUE TITLE
Provide a hook to insert custom express middleware

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#694]
The server set up by the CLI currently doesn't provide any way to insert custom _express_ middleware.

For example:

``` javascript
app.use(session(options))
```

**Comment by mlolson** [comment]
Question I was pondering: Would it be feasible to re-factor react server so that it could be used as middleware in an express application? Like:

    ReactServer = require('react-server');   
    //pagesDir tells react server where to find the routes file and pages...
    app.use(ReactServer({pagesDir: 'pages'});

In my experience it's easier to adopt something when you can use it within an existing framework like express, rather than having to buy the whole enchilada.

Does that make any sense? :)

**Comment by stanonyime** [comment]
My thoughts exactly

**Comment by gigabo** [comment]
Hi @mlolson that's actually possible already!  The CLI wraps that up for you, but at its core all it's doing is creating an express instance and [inserting middleware](https://github.com/redfin/react-server/blob/master/packages/react-server-cli/src/commands/start.js#L76) for you.  It looks a little funny, because it's inverted so the `app.use` happens inside of a method call, but this method call can go wherever you'd ordinarily want to put `app.use(ReactServer({routesFile: './routes.js'});`.

```javascript
app.use(ReactServer({routesFile: './routes.js'});
```

**Comment by mlolson** [comment]
Interesting! PS Is the README up to date? I tried to use the generator to get started but it seemed to fail.

**Comment by sresant** [comment]
@mlolson Hey! Sorry to hear you are having issues can you outline what the error is and the version of npm you are using? I recently filed a bug related to npm 6.2.2 #698.

**Comment by mlolson** [comment]
@sresant After I follow the instructions in the README, when I run `npm run start` it produces this error:

    Error: Cannot find module 'express'....

My directory doesn't look right. The app that is installed does not look like a react server app at all... Very odd

**Comment by doug-wade** [comment]
@mlolson almost certainly you've installed generator-react-server v1.0.0, which is an unrelated project.  We got the name from the very gracious @StevenIseki, but there are still some versions of of his previous project with that name on npm.  Make sure you have v0.4.13 installed before you scaffold out a new project.

**Comment by mlolson** [comment]
Lol! Thanks

**Comment by drewpc** [comment]
This has already been merged.  Closing.
