### ISSUE TITLE
Doc of `getMetaTags` not correct

### ISSUE THREAD

**Issue by mocheng** [redfin/react-server#789]
In https://github.com/redfin/react-server/blame/master/docs/page-api.md#L152-L155 , it reads
>getMetaTags(next: Function): Meta | Promise(Meta) | [Meta | Promise(Meta)]
A set of Meta objects that represent the meta tags for this page. If it’s a promise and the promise returns null, the meta tag will not be used.

However, if `getMetaTags` just return `Promise.resolve(null)`, it triggers an error
```
 [react-server.core.renderMiddleware] Error in renderPage chain message=Cannot read property 'name' of null, stack=TypeError: Cannot read property 'name' of null
```

I suppose the doc should be updated to be like "If it’s a promise and the promise returns empty array, the meta tag will not be used."

**Comment by gigabo** [comment]
Oh, nice catch @mocheng.  I wonder if we should fix the _docs_ here, or fix handling of `null`? :thinking: 

Given that the docs claim that `null` is supported I guess this is a regression?

**Comment by drewpc** [comment]
@mocheng Can you share your code that is creating the promise to be returned and resolving null?  I'm working on a test case to highlight this.

**Comment by drewpc** [comment]
Fixed.
