### ISSUE TITLE
Incorrect webpack configuration guidelines

### ISSUE THREAD

**Issue by kaytcat** [redfin/react-server#790]
The documentation for adding webpack configuration (https://github.com/redfin/react-server/blob/master/docs/guides/react-server-cli.md#webpack-options) is using camel case for defining the webpackConfig option which makes sense since the rest of the options are camel cased. However, I've found the option only works when written as "webpack-config".

I think maybe the code could be updated to use all camel cased options or at least the guide could reflect the correct options.

**Comment by feychou** [comment]
Related https://github.com/redfin/react-server/commit/a23199e5506794feeefca16228001645b19b1a27

**Comment by gigabo** [comment]
Ugh.  Thanks for reporting @kaytcat.

https://github.com/redfin/react-server/issues/783 would resolve this.
