### ISSUE TITLE
How do I set page title based on path of parameterized route?

### ISSUE THREAD

**Issue by jaredpalmer** [redfin/react-server#792]

**Comment by doug-wade** [comment]
Hi @jaredpalmer!  The [bike share example](https://github.com/redfin/react-server/blob/master/packages/react-server-examples/bike-share) does this.  To get the page title of the network page, I retrieve the [network name](https://github.com/redfin/react-server/blob/master/packages/react-server-examples/bike-share/pages/network.js#L13) in [handleRoute](https://react-server.io/docs/guides/writing-pages), and then retrieve it off the context in [getTitle](https://github.com/redfin/react-server/blob/master/packages/react-server-examples/bike-share/pages/network.js#L24)

**Comment by doug-wade** [comment]
Hi @jaredpalmer -- does [my earlier comment](https://github.com/redfin/react-server/issues/792#issuecomment-269071523) answer your question?  Can we close this issue?
