### ISSUE TITLE
default yeoman app includes a dependency that no longer exists (esprima-six)

### ISSUE THREAD

**Issue by helenaut** [redfin/react-server#793]
I followed the generation steps here: https://www.npmjs.com/package/generator-react-server

I think it's because browserify depends on derequire, which depends on esprima-six, which has been unpublished.

In general, the generator might benefit from a refresh, as it's still on React 12?

**Comment by doug-wade** [comment]
@helenaut I linked up generator-react-server and ran it, and also ran `npm uninstall -g yo && npm uninstall -g generator-react-server && npm i -g yo generator-react-server` and couldn't repro either way. Also, neither [npm](https://www.npmjs.com/package/generator-react-server) nor [github](https://github.com/redfin/react-server/blob/master/packages/generator-react-server/package.json#L25) shows browserify as a dependency.  Are you sure you didn't install `generator-reactserver`? Or `generator-react-server@1.0.0` (an unrelated package)?

**Comment by helenaut** [comment]
Did you try `yo react-server`? I see the error when I try doing that, not when I'm trying to install.
