### ISSUE TITLE
Possible react-server-cli improvements

### ISSUE THREAD

**Issue by jhnns** [redfin/react-server#794]
While reviewing #791 and looking at the code-base, I realized that there are some possible improvements from my point of view. Here, I tried to sketch some changes that I think would be useful. Depending on your feedback and my personal schedule, I can also start with PRs.

Since it seems that you are pretty confident about #791, I'm going to assume here that #791 has already been merged.

---

### Separate and refactor webpack config

Moved to #795

### Move express server to `react-server`

Moved to #796

### Separate build code from runtime code

Moved to #797

### Use multiple processes in development

Moved to #798

### Nitpick: Rename `__clientTemp` and separate client and server build

Moved to #799

### Nitpick: Remove `__reactServerBase`, `__setReactServerBase` and `__reactServerManifest` from `window`

Moved to #800

### Nitpick: Remove `compileOnly` option

Moved to #801

---

What do you think about these changes?

**Comment by doug-wade** [comment]
@jhnns I would definitely prefer to break this issue up into 7 separate issues -- trying to follow discussion in a single issue seems like it will quickly become overwhelming.

**Comment by doug-wade** [comment]
Thanks!
