### ISSUE TITLE
Question: should I merge my examples in?

### ISSUE THREAD

**Issue by aickin** [redfin/react-server#86]
I have [some example code](https://github.com/aickin/react-server-examples) that I'd love to donate to the project to help folks learn react-server, but I'm not sure if it's something that y'all want and/or where it would go.

@gigabo: in [this comment](https://github.com/redfin/react-server/pull/79#issuecomment-207032726), you said that "[t]hose are definitely better showcase examples than what I'm imagining here. I think they make sense to maintain as separate packages". I wasn't sure if that means you want me to keep them as separate packages in a separate repo, or that you mean they'd be welcome as sub-packages of the react-server monorepo. (I'm fine either way.)

So I'm looking for thoughts on if these would be a good addition to the monorepo, and if so, where they should go in the folder structure. Thanks!

**Comment by gigabo** [comment]
Oh, I meant a separate package in the monorepo!  `packages/react-server-examples`.  Bring it!

**Comment by aickin** [comment]
Closing, I got my answer and filed a PR. Thanks!
