### ISSUE TITLE
Errors in Js compliation in Windows 10

### ISSUE THREAD

**Issue by lxm7** [redfin/react-server#861]
When i run `npm run start` i get
`Error: Cannot resolve module 'C:Usersxxxworkspaceeact-server-core-middlewareindex.js  in C:\Users\xxx\workspace\react-server\__clientTemp
eact-serverule`

Is there a reason the path slashes are being removed?

This is also happening in the repo with even the simplest example https://github.com/redfin/react-server/tree/master/packages/react-server-examples/hello-world

Works in Linux

**Comment by drewpc** [comment]
This should've been fixed in version 0.60, released on Friday.  What version are you using?  See #832

**Comment by doug-wade** [comment]
we'll need to update https://github.com/redfin/react-server/blob/master/packages/react-server-examples/hello-world/package.json#L20 to 0.6.0, then.

**Comment by lxm7** [comment]
Thanks, now upgraded to 0.6.0

**Comment by breeswish** [comment]
Hi. I've updated to 0.6.0 but problem still exists. Any ideas? My project is generated by yoeman and I updated my `package.json` to the follows (and run `npm install`):

```json
{
  "name": "demo",
  "version": "0.0.1",
  "description": "A react-server instance",
  "main": "HelloWorld.js",
  "scripts": {
    "start": "react-server start",
    "lint": "eslint test.js pages",
    "test": "npm run lint && nsp check && ava test.js"
  },
  "license": "Apache-2.0",
  "dependencies": {
    "babel-preset-react-server": "^0.6.0",
    "babel-runtime": "^6.6.1",
    "react": "~15.4.2",
    "react-dom": "~15.4.2",
    "react-server": "^0.6.0",
    "react-server-cli": "^0.5.1",
    "superagent": "1.8.4"
  },
  "devDependencies": {
    "ava": "^0.18.0",
    "babel-eslint": "^7.1.0",
    "eslint": "3.14.1",
    "eslint-plugin-react": "6.9.0",
    "nsp": "^2.3.3"
  }
}
```

**Comment by breeswish** [comment]
Oh, strangely, `ncu` does not update my `react-server-cli` to `0.6.0`. Manually updating it to `0.6.0` fix this issue.

**Comment by doug-wade** [comment]
@breeswish what's `ncu`?

**Comment by breeswish** [comment]
Oops. Notification missed :(

I was using [node-check-updates (ncu)](https://www.npmjs.com/package/npm-check-updates) to update my `package.json`.
