### ISSUE TITLE
Drop babel-core in react-server-cli?

### ISSUE THREAD

**Issue by breeswish** [redfin/react-server#875]
`babel-core` is not recommended to use in production environment (which slows down `require()` a lot). However `react-server-cli` always includes it regardless of the current env.

**Comment by doug-wade** [comment]
iiuc, @drewpc is on the case: https://github.com/redfin/react-server/pull/869

**Comment by ptomasroos** [comment]
This should be closed now since #869 is merged?

**Comment by doug-wade** [comment]
Thanks @ptomasroos
