### ISSUE TITLE
Proposal: how to enable long-term caching of assets.

### ISSUE THREAD

**Issue by aickin** [redfin/react-server#88]
I'd like to write down a proposal I'm thinking of to implement far future caching in `react-server-cli` to get feedback before diving in. I have some worries about it, and I'd rather have some discussion before jumping in.

For background, read this [excellent article on how to implement long-term caching in webpack](https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95#.lhjhlr2eo); basically my proposal is just to implement everything in that article when in production mode (or when long-term caching's turned on by a flag).

Mostly this is fairly straightforward, but there is one wrinkle that I want to run by all of you. It's the case where you compile the client code ahead of time and upload the assets to a CDN or static server. Then you launch `react-server-cli` with `jsUrl: http://mycdn.com/my/precompiled/assets/`, and r-s-c launches just the HTML server, pointing all JS and CSS URLs at something like `http://mycdn.com/my/precompiled/assets/main.js`.

The problem in this case is that the HTML server needs to know about the output of the client webpack build in order to get the hashed names of both the entrypoint script files and the chunks that are loaded later. I can see two ways to do this:

1. **Decoupled**: Don't change the current compile codepath. When firing up a server with `jsUrl` set, run the compile codepath again just to get the file hashes (and throw away the actual assets).
1. **Manifest File**: When compiling the client code, output a `manifest.json` in the root directory that has all of the file hashes present. When firing up a server with `jsUrl` set, do NOT compile the client. Instead pull down the manifest file via HTTP(S) and use that to determine the file names.

I'm leaning towards a manifest file. If for whatever reason the client compilation was performed on a different version of the app codebase than what the server is attempting to run, we could detect that case using the manifest file and warn or refuse to start up at all. I'm sure that client/server version mismatches would create wildly hard to find bugs.

I also have some worries about the manifest file, particularly that requiring there to be a network path from the HTML server to the static file server might trip some folks up. Thoughts?

**Comment by roblg** [comment]
We actually implemented something like this internally that sounds similar to option 2. We have a roughly five line webpack plugin that outputs a file called `assetsByChunkName.json` that we use to tell the server about the entrypoints. For lazy-loaded JS bundles, webpack keeps its own mappings internally, and just knows what files to load. AFAIK, we don't use the `assetsByChunkName.json` file on the client at all. (cc @bartkusa, who worked on this originally)

**Comment by aickin** [comment]
Thanks, @roblg!

>  For lazy-loaded JS bundles, webpack keeps its own mappings internally, and just knows what files to load.

 FYI, [the Medium article I linked to above](https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95#.xym8wfaas) explains that this is not enough to keep the hashes constant from build to build; any change to any module changes all the hashes of all entry chunks, even if the entry chunk doesn't include that module. You have to use `ChunkManifestPlugin` as well; see the section on "Deterministic Hashes".

Any thoughts on using HTTP(S) to download a manifest when the client build is being served up by another server?

**Comment by roblg** [comment]
Interesting. We definitely expected to have issues w/ non-deterministic behavior, and looked for it, and didn't find it. Although I think we were worried about hashes changing for no reasons. Maybe they _all_ change if _any_ file changes? I don't recall if we checked for that (but @bartkusa may remember).

There's a comment from sokra on [the issue](https://github.com/webpack/webpack/issues/950#issuecomment-129166959) linked in the blog post saying that occurrence order is the default. (And then some comments from people after that saying they're still experiencing the issue, though maybe in very particular circumstances.) So maybe it's fixed, maybe not? If we can get away with not adding a dependency on YAWP (Yet Another Webpack Plugin), that would be my preference. IME, the more plugins you have in the build, the more bugs you find in plugins in the build. :)

In any event, to answer your actual question: I don't think see a problem with downloading the file from the static content server at startup.

Alternatively, what's preventing us from just outputting the file in the frontend build, and then having that file copied into the server deploy tar or whatever as a step outside r-s-c? Just convenience?

**Comment by aickin** [comment]
> Although I think we were worried about hashes changing for no reasons. Maybe they all change if any file changes?

Yeah, this issue is not about non-determinism from one build to the next when the code doesn't change. It's about a small code change changing all hashes for all chunks, including completely unrelated ones. To quote the article: 

> The problem with this is the same as before: whenever we change any part of the code, it will, even if the rest of its contents wasn’t altered, update our entry chunk to include the new manifest.

The problem is that every entry chunk keeps a map of all chunk names, which of course includes the chunk hashes in the chunk names. So, when any chunk changes, its hash changes, which means that the chunk name map changes, which changes the text of the entry chunk, which changes the entry chunk's hash. Yay.

> There's a comment from sokra on the issue linked in the blog post saying that occurrence order is the default. (And then some comments from people after that saying they're still experiencing the issue, though maybe in very particular circumstances.) So maybe it's fixed, maybe not?

Occurrence order is a different problem, which can cause hashes to change **between different builds of the same codebase**. You also need the OccurrenceOrderPlugin (which also is in the linked article).

In that thread, sokra says it's on by default in the next **major** version (i.e. webpack 2), which is confirmed in [this webpack 2 feature list](https://gist.github.com/sokra/27b24881210b56bbaff7#occurrence-order).

> what's preventing us from just outputting the file in the frontend build, and then having that file copied into the server deploy tar or whatever as a step outside r-s-c? 

I'm trying to decide what to do when react-server-cli is used to build the client code separately from starting up the HTML server, [as described here](https://github.com/redfin/react-server/tree/master/packages/react-server-cli#building-static-files-for-production-use) in the docs. I suppose those instructions could be changed to say something like "step 2.5: Copy manifest.json to your server somewhere" and then "step 3: when you start up the HTML server, pass the manifest file in at the command line using --manifest=location/of/manifest.json along with jsUrl". Is that what you mean?

**Comment by roblg** [comment]
re: determinism - Le sigh. I suppose we probably have a bug to fix now internally as well.

> I suppose those instructions could be changed to say something like "step 2.5: Copy manifest.json to your server somewhere" and then "step 3: when you start up the HTML server, pass the manifest file in at the command line using --manifest=location/of/manifest.json along with jsUrl".

Yep, that's what I was thinking. That's basically what we do today internally. I'm assuming that there should be another step somewhere in there that's like "copy your server code to <not the static file server>" as well, right? I would think it would go along with that.

**Comment by gigabo** [comment]
> YAWP

😆 ... 😂 ... 😢

**Comment by gigabo** [comment]
@aickin - Was this covered by #96, or is there more you'd like to see done here?

**Comment by aickin** [comment]
Sorry, yeah, I think this is covered. Closing!

**Comment by gigabo** [comment]
Thanks!
