### ISSUE TITLE
generator disables hot reloading; docs say it's enabled

### ISSUE THREAD

**Issue by dfabulich** [redfin/react-server#888]
To repro:

Run the yeoman generator steps from https://react-server.io/ to start a server
Open http://localhost:3000 in your browser
Modify the `components/hello-world.js` to replace "World" with "Earth" and save

Expected: The page should "hot reload." Without even refreshing your browser, you should see the word "World" replaced with "Earth." The [generated documentation](https://github.com/redfin/react-server/blob/master/packages/generator-react-server/generators/app/templates/README.md) says hot reloading is enabled:

> You will see a simple page that pre-renders and that is interactive on load. It also will include hot reloading of React components in their own file.

Actual: The generator disables hot reloading by default.

https://github.com/redfin/react-server/blob/master/packages/generator-react-server/generators/app/templates/_reactserverrc
```
"hot": false,
```

**Comment by gigabo** [comment]
Nice catch @dfabulich.  These should be consistent.

In the future if you have a patch ready please don't bother with a separate issue.  A PR is worth a thousand issues!

**Comment by roblg** [comment]
Closed by #889
