### ISSUE TITLE
Do something about config.js

### ISSUE THREAD

**Issue by gigabo** [redfin/react-server#91]
This [config.js](https://github.com/redfin/react-server/blob/master/packages/react-server/core/config.js) is cool.  It allows sites to specify config that's available both server side and in the browser.

But we _also_ have [a config file](https://github.com/redfin/react-server/pull/87) for the server itself, which _doesn't_ make sense to transfer to the browser.

Two config files seems weird.  Do we need both?  Can we merge them cleanly somehow?

More discussion [here](https://github.com/redfin/react-server/pull/87#issuecomment-208647869).

**Comment by drewpc** [comment]
The separation that I see between these two is that `.reactserverrc` allows me to configure `react-server` whereas the config.js stuff allows me to configure my own application in an isomorphic fashion.  Meaning: they accomplish two different things.  There's been no further action on this in almost a year, so I'm closing this.
