### ISSUE TITLE
Client side getQuery() includes fragment identifers in parsed query parameters

### ISSUE THREAD

**Issue by edsonlo** [redfin/react-server#938]
Let's say you submit a url like `http://www.domain.com/page?param1=xyz&param2=123#anchor`. Calling `getQuery()` results in parameters `{param1: "xyz", param2: "123#anchor"}` when `{param1: "xyz", param2: 123}` is expected.

**Comment by gigabo** [comment]
Nice find @edsonlo!

Looks like this is browser-side only.  Likely here (in `ClientRequest.js`):

```js
    getQuery() {
        var indexOfQuestion = this._url.indexOf("?");
        if (-1 === indexOfQuestion) {
            return {};
        }
        return decode(this._url.substring(indexOfQuestion + 1));
    }
```
